### ISSUE TITLE
NIP-42

### ISSUE THREAD

**Issue by npub1zenn0** [adamritter/nostr-relaypool-ts#39]
NIP-42 was added to nostr-tools. Would be nice to have it here too.

It works about as follows:

```ts
import { nip42 } from 'nostr-tools';

relay.on('auth', challenge => nip42.authenticate({ relay, challenge, sign }))
```

Thoughts on best approaches here? Probably like `.onauth` since there is `.onnotice` etc. already? I didn't check any code here yet, thought I'd open up an issue first.

**Comment by adamritter** [comment]
Sure, sounds great, if you like it and works for your program, I'd be happy to merge a pull request that implements it.
